version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: shopdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    command: flask run --host=0.0.0.0 --port=5000

#  worker:
 #   build:
 #     context: .
  #    dockerfile: Dockerfile
 #   env_file:
 #     - .env
 #   depends_on:
 #     - db
 #     - redis
 #   command: python worker.py
 #   volumes:
 #     - ./:/app

# nếu bạn có frontend container thay vì phục vụ bằng Flask static, thêm ở đây:
#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./frontend:/app

volumes:
  db-data:
